apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2024-01-11T14:27:29Z"
  name: svc-blue
  namespace: user-00
  resourceVersion: "155298"
  uid: ca3ae526-217f-4812-b864-dddb0d255f6e
spec:
  host: svc-blue-user-00.apps.cluster1.openshift.vms.sass.ro
  port:
    targetPort: 8080
  to:
    kind: Service
    name: svc-blue
    weight: 100
  wildcardPolicy: None