apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-lab
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: alpine
            args:
            - date
          restartPolicy: Never