apiVersion: v1
kind: Pod
metadata:
  name: alpine02
spec:
  containers:
    - image: alpine
      name: alpine
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /scratch
          name: empty-volume
  volumes:
    - name: empty-volume
      emptyDir: {}
