apiVersion: v1
kind: Pod
metadata:
  name: cmap-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: k8s-adv
  restartPolicy: Never
