apiVersion: v1
kind: Pod
metadata:
  name: secretpod
spec:
  containers:
  - name: alpine
    image: alpine
    stdin: true
    tty: true
    volumeMounts:
    - name: dbpass
      mountPath: "/etc/secret"
      readOnly: true
  volumes:
  - name: dbpass
    secret:
      secretName: db-conn-data