apiVersion: v1
kind: Pod
metadata:
  name: secretpod-02
spec:
  containers:
  - name: alpine
    image: alpine
    stdin: true
    tty: true
    command: ["echo"]
    args: ["I know a secret: Username is $(DBUSER), password is $(DBPASS)!"]
    env:
    - name: DBUSER
      valueFrom:
        secretKeyRef:
          name: db-conn-data
          key: username.txt
    - name: DBPASS
      valueFrom:
        secretKeyRef:
          name: db-conn-data
          key: password.txt