apiVersion: v1
kind: Pod
metadata:
  name: alpine-secret
spec:
  restartPolicy: Never
  containers:
  - name: alpine
    image: alpine
    args:
    - cat
    - /appconfig/config.txt
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 1000
      capabilities:
        drop: ["ALL"]
      seccompProfile: 
        type: RuntimeDefault
    volumeMounts:
    - name: config-volume
      mountPath: "/appconfig"
  volumes:
  - name: config-volume
    secret:
      secretName: secret-01
