apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-01
  namespace: user-03
spec:
  version: 8.12.0
  count: 1
  elasticsearchRef:
    name: es-cluster-01
    namespace: user-03
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2Gi
            cpu: 2
  # Disable HTTPS to allow kibana access over ingress
  http:
    tls:
      selfSignedCertificate:
        disabled: true
