apiVersion: v1
kind: Pod
metadata:
  name: nginx01
spec:
  containers:
    - image: bitnami/nginx
      name: nginx
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 1000
        capabilities:
          drop: ["ALL"]
        seccompProfile: 
          type: RuntimeDefault
          