apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
    - name: web
      image: bitnami/nginx
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop: ["ALL"]
        seccompProfile: 
          type: RuntimeDefault 
  nodeSelector:
    training.sass.ro/k8slab: preferred
    