apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-depl
  template:
    metadata:
      labels:
        app: nginx-depl
    spec:
      nodeSelector:
        cpus: "4"
      containers:
      - name: nginx
        image: nginx:1.14.0

