apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservers
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-depl
  template:
    metadata:
      labels:
        app: nginx-depl
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cpus
                operator: In
                values:
                - "4" 
      containers:
      - name: nginx
        image: nginx:1.14.0

