apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webservers
  template:
    metadata:
      labels:
        app: webservers
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cpus
                operator: In
                values:
                - "4"
      containers:
      - name: nginx
        image: bitnami/nginx
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
          seccompProfile: 
            type: RuntimeDefault 