apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webservers
  template:
    metadata:
      labels:
        app: webservers
    spec:      
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - webservers
              topologyKey: topology.kubernetes.io/zone  
      containers:
      - name: nginx
        image: bitnami/nginx
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
          seccompProfile: 
            type: RuntimeDefault 