apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:      
      containers:
      - name: gows
        image: bogd/go-webserver
        resources:
          requests:
            cpu: 100m
            memory: 32Mi
          limits:
            cpu: 300m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
          seccompProfile: 
            type: RuntimeDefault 