kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-pod-viewers
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-viewer
roleRef:
  kind: Role
  name: pod-reader 
  apiGroup: rbac.authorization.k8s.io

